[plugin]
summary = 'Casbin RBAC'
version = '0.0.1'
description = '基于 Casbin 实现的 RBAC 访问控制'
author = 'wu-clan'

[app]
include = 'admin'

[api.api]
prefix = '/apis'
tags = '系统API'

[api.casbin]
prefix = '/casbin'
tags = '系统Casbin权限'
